### ISSUE TITLE
konferenz.fossgis.de nach fossgis-konferenz.de/2020 weiterleiten

### ISSUE THREAD

**Issue by simon04** [fossgis/fossgis-webseite#22]
Über meine Historie meines Webbrowsers habe ich http://konferenz.fossgis.de/ gefunden. Dort wird die Konferenz-Seite 2019 geladen. Eine Weiterleitung nach https://fossgis-konferenz.de/2020/ wäre praktisch. Danke!

**Comment by pka** [comment]
http://konferenz.fossgis.de/ und https://fossgis-konferenz.de/ werden jetzt auf die aktuelle Konferenz-Seite weitergeleitet.
