### ISSUE TITLE
Links auf unter Verein - Kontakt kaputt

### ISSUE THREAD

**Issue by GeoDodo** [fossgis/fossgis-webseite#23]
Die Links „Mailinglisten“ uns „Chat“ führen momentan ins Leere.

https://www.fossgis.de/verein/kontakt/

**Comment by astroidex** [comment]
Korrektur erfolgte im commit: https://github.com/fossgis/fossgis-webseite/commit/02944b5a946da290ea67ea5b233546539a98dfdc

Sorry. Hab zu schnell geklickt und daher keinen branch/PR erstellt.
