### ISSUE TITLE
Vectorized logo

### ISSUE THREAD

**Issue by loleg** [fossgis/fossgis-webseite#49]
@katjahafi I noticed you recently uploaded [a logo](https://github.com/fossgis/fossgis-webseite/tree/master/static/logos) for the 2021 event, which looks great and is high-res, but it would be appreciated if this was also available in vector (SVG, EPS, ..) format. Thanks!

**Comment by katjahafi** [comment]
> @katjahafi I noticed you recently uploaded [a logo](https://github.com/fossgis/fossgis-webseite/tree/master/static/logos) for the 2021 event, which looks great and is high-res, but it would be appreciated if this was also available in vector (SVG, EPS, ..) format. Thanks!

what is it for? The SVG-File is here: https://www.fossgis.de/mediawiki/images/a/a8/FOSSGIS_Konferenz_Logo_2021.svg

**Comment by loleg** [comment]
It's for the FOSSGIS appreciation society ;-) Many thanks!
