### ISSUE TITLE
Access & workflow

### ISSUE THREAD

**Issue by nilsnolde** [fossgis/fossgis-webseite#64]
@pka can you quickly summarize the important steps how this repo/hugo works?

If Katja pushes here to `master`, what's happening? Is there a webhook that's doing some request on pushes or how does web2.fossgis.de get updated?

**Comment by nilsnolde** [comment]
@katjahafi tried to publish an article in `/news` but it didn't work apparently. I wonder where the magic happens? Not in Github Actions..

**Comment by Nakaner** [comment]
There might be a script on the web server itself.

**Comment by nilsnolde** [comment]
At least nothing in cron.. Also that wouldn't update things instantly, which seemed to have been the case so far. But I'm not an admin here, so I can't see if there's webhooks set up. Not very familiar with hugo, well not at all..

**Comment by nilsnolde** [comment]
Ah, meine Augen haben nur den cron job gesehen. Hm, seltsam, wieso sehe ich nix in Actions tab von master pushes?

**Comment by katjahafi** [comment]
Die Frage ist, warum wird die heute erstellte News nicht auf die Webseite übernommen?

Nächste Frage: Beim Kalender werden die vergangenen Termine herausgenommen. Der Termin FOSSGIS-Konferenz ist vergangen und immer noch angezeigt. Ist da ein Zusammenhang?

**Comment by pka** [comment]
Beim Push davor lief der Workflow noch: https://github.com/fossgis/fossgis-webseite/actions/runs/3895457750

Offenbar war er auch für Pushes disabled😯

**Comment by nilsnolde** [comment]
Walhalla😂

Hört sich nach Github Bug an.. Kannst du mal probieren @katjahafi mit „git commit --allow-empty -m "Trigger Build" && git push“? Dann sollte es ja wieder klappen.

**Comment by katjahafi** [comment]
läuft, vielen Dank.
